# Generated by Django 5.2 on 2025-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_book_on_sale_book_sale_end_book_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
