# Generated by Django 5.2 on 2025-05-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_book_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sale_price',
        ),
    ]
